version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8012:8012
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
    command: uvicorn app:app --host 80.89.228.71  --reload


