services:
  app:
    image: lochinbek/fastapi
    container_name: fastapi-container
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - .:/code
