version: '3.7'

services:
  django_gunicorn:
    volumes:
      - .:/app
    env_file:
      - .env 
    build: 
      context: .
    ports:
      - "9090:9090"
  nginx:
    build: ./nginx
    ports:
      - "85:85"
    depends_on:
      - django_gunicorn